books/urls.py
from . import views
from django.urls import path

app_name = "books"

urlpatterns = [
    path('', views.index, name='homepage'),
    path('add', views.create_book, name="book-add"),
    path('register', views.register, name='register'),
#    path('login', views.login_user, name='login'),
#    path('logout', views.logout_user, name='logout'),
    path('<int:book_id>/borrow', views.borrowBook, name='borrow'),
    path('<int:book_id>/borrow_req', views.borrow_req, name='borrow_req'),
    path('<int:book_id>/return', views.returnBook, name='return'),
    path('<int:book_id>/return_req', views.return_req, name='return_req'),
    path('<int:book_id>/delete', views.deleteBook, name='delete'),
    path('<int:user_id>/borrowed', views.borrowed, name='borrowed'),
    path('search', views.search, name='search'),
    path('addmanually', views.create_book_manually, name="book-addman"),
    path('confirm', views.confirm_book, name="confirm"),
    path('howto', views.howto, name="howto"),
    path('<int:user_id>/ownedbooks', views.ownedbooks, name="ownedbooks"),

#    path('devoterlist',views.devoterlist,name = 'devoter')
    ]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import books.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', books.views.top, name='top'),    
    path('books/', include("books.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Book(models.Model):
    CHOICES = (
        (11, 'Tokyo'),
        (12, 'Osaka'),
        (13, 'Fukuoka'),
        (21, 'Berlin'),
        (22, 'Hamburg'),
    )

    isbn = models.CharField(max_length=30)
    title = models.CharField(max_length=250)
    cover_url = models.URLField(blank=True)
    cover_image = models.ImageField(upload_to='images/')
    author = models.CharField(max_length=100, default="unknown")
    publisher = models.CharField(max_length=100, default="unknown")
    quantity = models.IntegerField(default=1)
    pubdate = models.CharField(max_length=20)
    regdate = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.IntegerField(
        choices=CHOICES,
        default=21
    )

    def get_absolute_urls(self):
        return reverse(
            "books:detail",
            kwargs={'pk': self.pk}
        )

    def __str__(self):
        return self.title


class BorrowRecord(models.Model):
    Borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    BookBorrowed = models.ForeignKey(Book, null=True, on_delete=models.CASCADE)
    BeginTime = models.DateTimeField(auto_now_add=True)
    EndTime = models.DateField(null=True, blank=True)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.Borrower.username + " borrowed " + self.BookBorrowed.title

books/views.py
# from django.views import generic
# from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from django.contrib.auth.models import User
# from django.http import HttpResponse, Http404
# from django.shortcuts import render, get_object_or_404
# from django.urls import reverse, reverse_lazy
# import urllib.request
# from PIL import Image
# import os
# from django.core.files import File

from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.core.files.base import ContentFile
import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import date
from django.core.mail import EmailMessage

from .models import Book, BorrowRecord
from .form import UserForm, BookForm
from . import openbd
from . import rakutenapi


# Create your views here.

all_book = Book.objects.all()


def query_borrowed(user_id):
    books = Book.objects.all()
    

def query_book(query):
    books = Book.objects.all()
    books = books.filter(
        Q(title__icontains=query) |
        Q(author__icontains=query) |
        Q(publisher__icontains=query)
    ).distinct()
    # books.filter(~Q(quantity=0))
    return books


def top(request):
    # ToDo filter books
    books = Book.objects.all()

    return render(request, 'book/top.html', {'books': books})


@login_required(login_url='/')
def index(request):
    query = request.GET.get("q")
    if query:
        books = query_book(query)
        return render(request, 'book/homepage.html', {
            'books': books,
        })
    else:
        # books = Book.objects.filter(~Q(quantity = 0))
        # books = Book.objects.all()
        books = Book.objects.order_by('-regdate')[:20]
        return render(request, 'book/homepage.html', {'books': books})


# def Detail(request,book_id):
#     if not request.user.is_authenticated:
#         return HttpResponseRedirect('book/login')
#     else:
#         book = get_object_or_404(Book, pk=book_id)
#         context = {
#             'book' : book,
#         }
#         return render(request,'book/item.html',context)


@login_required(login_url='/accounts/login/')
def create_book(request):
    form = BookForm(request.POST or None, request.FILES or None)
    # info = request.POST.copy()
    if form.is_valid():
        # print(info)
        # print(info.__getitem__('isbn'))
        book = form.save(commit=False)

        # If same isbn & owner, count up
        thisISBN = book.isbn
        existingISBN = Book.objects.filter(isbn=thisISBN, owner=request.user)
        # existingTitle = Book.objects.filter(title=book.title)
        if existingISBN.count() > 0:
            existingbook = existingISBN[0]
            existingbook.quantity += 1
            existingbook.save()

            messages.success(
                request, 'The book ' +
                '{} was successfully counted up!'.format(book.title))

            return HttpResponseRedirect('/books')
    
        book.owner = request.user
        book.save()

        # Get image file from external url
        response = requests.get(book.cover_url)
        filename = str(book.id) + '_frontpage.jpg'
        book.cover_image.save(filename, ContentFile(response.content),
                              save=True)
        book.save()

        messages.success(request, 'The book ' +
                         '{} was successfully added!'.format(book.title))

        return HttpResponseRedirect('/books')
    else:
        # If form is not fulfilled
        return render(request, 'book/add_book.html')


@login_required(login_url='/accounts/login/')
def borrowBook(request, book_id):
    """borrowed a book"""
    borrowRecords = BorrowRecord.objects.filter(
        Borrower=request.user
        ).filter(finished=False)
    
    # Limited the number to borrow a same book
    if borrowRecords.count() > 4:
        messages.warning(request, "You have already borrowed 5 books.")
        return HttpResponseRedirect('/books')
    
    borrowed_books = set()
    for record in borrowRecords:
        borrowed_books.add(record.BookBorrowed.pk)
    if book_id in borrowed_books:
        messages.warning(request, 'You have already borrowed this book.')
        return HttpResponseRedirect('/books')

    user = request.user
    book = Book.objects.get(pk=book_id)

    if book.owner == request.user:
        messages.warning(request, "You cant't borrow your own book.")
        return HttpResponseRedirect('/books')

    record = BorrowRecord(Borrower=request.user, BookBorrowed=book)
    if book.quantity >= 1:
        book.quantity -= 1
        book.save()
        record.save()

        email = EmailMessage(
            '{} has borrowed {}'.format(request.user.first_name, book.title),
            '*** This is automatically generated email, please do not reply ***\n',
            to=[book.owner.email,],
            cc=[request.user.email,],
        )
        email.send()

        messages.success(request, 'You have borrowed ' +
                         '{} !'.format(book.title))
        return HttpResponseRedirect("/books/%d/borrowed" % user.id)
    else:
        # not used the book can't be borrowed if quantity = 0.
        messages.warning(request, 'This book is unavailable now.')
        return HttpResponseRedirect('/books')


@login_required(login_url='/accounts/login/')
def returnBook(request, book_id):
    borrowRecords = BorrowRecord.objects.filter(Borrower=request.user)
    borrowed_books_id = set()
    for record in borrowRecords:
        borrowed_books_id.add(record.BookBorrowed.pk)
    # borrowed_books = Book.objects.filter(pk__in=borrowed_books_id)

    if book_id not in borrowed_books_id:
        return HttpResponseRedirect('/books/%d/borrowed' % request.user.id)
    else:
        # print('success')
        thisRecord = BorrowRecord.objects.filter(
            Borrower=request.user,
            BookBorrowed=Book.objects.get(id=book_id)
            ).filter(finished=False)

        thisRecord = thisRecord[0]
        source = Book.objects.get(id=thisRecord.BookBorrowed.id)
        source.quantity += 1
        source.save()

        thisRecord.EndTime = date.today()
        thisRecord.finished = True
        thisRecord.save()

        email = EmailMessage(
            '{} has returned {}'.format(request.user.first_name, source.title),
            '*** This is automatically generated email, please do not reply ***\n',
            to=[source.owner.email,],
            cc=[request.user.email,],
        )
        email.send()

        messages.success(request, 'You have returned ' +
                         '{} !'.format(source.title))

        # return render(request, 'book/borrowed.html',
        #           {'books': borrowed_books})
        print('here')
        return HttpResponseRedirect('/books/%d/borrowed' % request.user.id)


@login_required(login_url='/accounts/login/')
def borrowed(request, user_id):
    books = Book.objects.all()
    query = request.GET.get("q")
    if query:
        books = query_book(query)

    borrowRecords = BorrowRecord.objects.filter(
        Borrower=request.user
        ).filter(finished=False)
    
    borrowed_books_id = set()

    for record in borrowRecords:
        borrowed_books_id.add(record.BookBorrowed.pk)

    borrowed_books = books.filter(pk__in=borrowed_books_id)

    return render(request, 'book/borrowed.html',
                  {'books': borrowed_books})


def register(request):

    form = UserForm(request.POST or None)

    if form.is_valid():
        user = form.save()
        login(request, user)
        return HttpResponseRedirect('/books')

    return render(request, 'book/register.html', {'form': form})

# def devoterlist(request):
#    if not request.user.is_authenticated:
#        return HttpResponseRedirect("/books/login")
#    else:
#        context = {
#            'all_records': DevoteRecord.objects.all(),
#        }
#        return render(request,'book/devote.html',context)


@login_required(login_url='/accounts/login/')
def search(request):
    if request.method == 'GET':
        isbn = request.GET.get('isbn', False)

        isbn = isbn.replace('-', '')

        if not isbn.isdigit() or len(isbn) != 13:
            messages.warning(
                request, 'The isbn code should be 13 digits'
                )
            return render(request, 'book/add_book.html')

        api = openbd.openBD()
        data = api.get_json(isbn)

        # if openBD data is None or cover of openBD is blank
        if data is None or data['cover'] == '':
            rakuten_api = rakutenapi.rakuten()
            data = rakuten_api.get_json(isbn)

        # if data is None
        if data is None:
            messages.warning(request, 'The book was not found!')
            return render(request, 'book/add_book.html')

        form = BookForm({
            'isbn': data['isbn'],
            'title': data['title'],
            'cover_url': data['cover'],
            'author': data['author'],
            'publisher': data['publisher'],
            'pubdate': data['pubdate'],
            'location': 21,
            })
        return render(request, 'book/confirm_book.html',
                      {'form': form, 'cover_url': data['cover']})


@login_required(login_url='/accounts/login/')
def create_book_manually(request):
    f = BookForm()
    return render(request, 'book/confirm_book.html', {'form': f})
    # return render(request, 'book/add_book_manually.html', {'form': f})


@login_required(login_url='/accounts/login/')
def confirm_book(request):
    print('book confirm')
    return HttpResponseRedirect("/books")


def howto(request):
    return render(request, 'book/howto.html')


@login_required(login_url='/accounts/login/')
def ownedbooks(request, user_id):
    books = Book.objects.all()
    query = request.GET.get("q")
    if query:
        books = query_book(query)

library/templates/book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Biblio{% endblock %}</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" class="mx-auto" href="{%  static 'logo.png' %}"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  
  <link href="{% static 'open-iconic-master/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet">

  <link href="{% static 'css/faq.css' %}" rel="stylesheet">

  <style type="text/css"><!--
  .jumbotron {
    background: white url("/static/books_background3.jpg") center no-repeat; background-size: cover;}
  --></style>

</head>
  

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }
    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  
</head>


<body>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <!-- Items -->
      <a class="navbar-brand" href="{% url 'books:homepage' %}">
        <img src="{% static 'logo_w.png'%}" height=30 class="mx-auto d-block align-center rounded" />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:book-add' %}">
              <span class="oi oi-plus"  title="Add" aria-hidden="true"></span> Add
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:borrowed' user.id %}">
              <span class="oi oi-book"></span> Borrowed
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:ownedbooks' user.id %}">
              <span class="oi oi-book"></span> Owned
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'books:howto'%}">
              <span class="oi oi-question-mark"></span> HowTo
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout'%}"> Logout
            </a>
          </li>
          {% else %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'books:register'%}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>          
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <span class="navbar-text">
          <span class="oi oi-person" title="user" aria-hidden="true" ></span>
          <span class="mr-3">{{ user.first_name }}</span>
        </span>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" name = 'q' value="{{ request.GET.q }}" placeholder="title，author，ISBN" aria-label="Search">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>
  {% block body %}
  {% endblock %}
  <footer class="text-muted">
    <div class="container text-center">
      <p>© Biblio {% now "Y" %}</p>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('li.active').removeClass('active');
      $('a[href="' + location.pathname + '"]').closest('li').addClass('active'); 
    });
  </script>

</body>

</html>